### ISSUE TITLE
Error in `tarantool binary.lua <running>': malloc(): memory corruption

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/memcached#18]
```
cd test
./test-run.py --gdb
screen -r
```

```
*** Error in `tarantool binary.lua <running>': malloc(): memory corruption: 0x0000000000894f30 ***

Program received signal SIGABRT, Aborted.
0x00007ffff5d85657 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5d85657 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff5d86a2a in __GI_abort () at abort.c:89
#2  0x00007ffff5dc3bb3 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff5ebc5f8 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff5dc900e in malloc_printerr (action=1, str=0x7ffff5eb8808 "malloc(): memory corruption", ptr=<optimized out>) at malloc.c:4965
#4  0x00007ffff5dca86f in _int_malloc (av=av@entry=0x7ffff60f0c00 <main_arena>, bytes=bytes@entry=304) at malloc.c:3441
#5  0x00007ffff5dcd4e5 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3213
#6  0x00007ffff51c3d34 in memcached_create (name=0x400e9ed0 "memcached", sid=512)
    at /mnt/data/data/Projects/MRU/tarantool/memcached/memcached/internal/memcached.c:230
#7  0x00000000004e9864 in lj_vm_ffi_call () at buildvm_x86.dasc:2575
#8  0x0000000000508675 in lj_ccall_func (L=L@entry=0x40000378, cd=<optimized out>) at lj_ccall.c:962
#9  0x00000000004e5726 in lj_cf_ffi_meta___call (L=0x40000378) at lib_ffi.c:230
#10 0x00000000004e78c7 in lj_BC_FUNCC () at buildvm_x86.dasc:809
#11 0x000000000050e8a0 in lj_cf_dofile (L=0x40000378) at lib_base.c:423
#12 0x00000000004e78c7 in lj_BC_FUNCC () at buildvm_x86.dasc:809
#13 0x00000000004d3921 in lua_pcall (L=L@entry=0x40000378, nargs=<optimized out>, nresults=nresults@entry=0, errfunc=errfunc@entry=0) at lj_api.c:1055
#14 0x00000000004ab755 in lbox_call (L=L@entry=0x40000378, nargs=<optimized out>, nreturns=nreturns@entry=0)
    at /home/travis/build/tarantool/tarantool/build/root/deb-debian-stretch/tarantool-1.6.8.499/src/lua/utils.c:936
#15 0x00000000004a6639 in run_script_f (ap=<error reading variable: value has been optimized out>)
    at /home/travis/build/tarantool/tarantool/build/root/deb-debian-stretch/tarantool-1.6.8.499/src/lua/init.c:497
#16 0x0000000000425b8c in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=<optimized out>, ap=<optimized out>)
    at /home/travis/build/tarantool/tarantool/build/root/deb-debian-stretch/tarantool-1.6.8.499/src/fiber.h:527
#17 0x00000000004b5930 in fiber_loop (data=<optimized out>)
    at /home/travis/build/tarantool/tarantool/build/root/deb-debian-stretch/tarantool-1.6.8.499/src/fiber.c:462
#18 0x0000000000575f4f in coro_init () at /home/travis/build/tarantool/tarantool/build/root/deb-debian-stretch/tarantool-1.6.8.499/third_party/coro/coro.c:110
```

**Comment by bigbes** [comment]
Fixed in latest master
