### ISSUE TITLE
Using PHP connector leads to a tarantool crash

### ISSUE THREAD

**Issue by R-omk** [tarantool/memcached#19]
```php
<?php
// php5 or php7
$memcacheD = new Memcached;   //$memcacheD = new Memcache;   // Both drivers cause the same effects
$memcacheD->addServer('192.168.56.1', 11211);
$memcacheD->set('k1', 'v1'); //  $x = $memcacheD->get('k1');   //   Any command leads to crash
```

```
tnt_memcached | Segmentation fault
tnt_memcached | Current time: 1458824739
tnt_memcached | Please file a bug at http://github.com/tarantool/tarantool/issues
tnt_memcached | Attempting backtrace... Note: since the server has already crashed, 
tnt_memcached | this may fail as well
tnt_memcached | #0  0x427cc0 in sig_fatal_cb(int)+112
tnt_memcached | #1  0x7f51232ef340 in ?
tnt_memcached | #2  0x7f512185f965 in ?
tnt_memcached | #3  0x7f512185fcb3 in ?
tnt_memcached | #4  0x7f5121861b86 in ?
tnt_memcached | #5  0x4e1974 in lj_vm_ffi_call+132
tnt_memcached | #6  0x4ffc8e in lj_ccall_func+942
tnt_memcached | #7  0x4dd818 in lj_cf_ffi_meta___call+56
tnt_memcached | #8  0x4df9d7 in lj_BC_FUNCC+52

```

**Comment by bigbes** [comment]
Problem was due to Tarantool 1.6.7 was used with latest memcached library.
